<footer class="footer footer-comp">
  <p>
    Made by Brianna Renni 💜
    <a href="https://github.com/briannarenni/" target="_blank">Github</a>
  </p>
</footer>

<style>
  .footer {
    border-block: 1px solid var(--off-white);
    color: var(--gray-blue);
    font-size: 15px;
    text-align: center;
    padding-block: var(--spacing-sm);
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
  }

  .footer a {
    color: var(--action-text);
  }

  .footer a:hover {
    color: var(--action-text);
    font-weight: bold;
  }
</style>
